package com.vemser.chat.kafka.chatkafka.dto;

public enum NomeChat {

    AA_GERAL, // 0
    RAFA, // 1
    MAY, // 2
    ANDERSON_LUIZ_TURKIEWICZ,
    ANDRÉ_LUIZ_MARQUES_MIRANDA,
    ANGELO_ANTONIO_DOS_SANTOS_PINTO,
    CARLOS_HENRIQUE_ALEXANDRE_QUEIROZ,
    CECÍLIA_SILVA,
    DAVID_WINTER_KIRSCH,
    DEYVID_LUCAS,
    DIULIANO_VARGAS_DA_SILVEIRA,
    GABRIEL_ANTONIO_NUNES_DE_SOUZA,
    GABRIEL_ZAMPIERI,
    GREICE_KELLY_SILVA_DA_ROSA,
    HILDÉLIO_FRANCISCO_DOS_SANTOS_JUNIOR,
    ÍCARO_LEON,
    LEONARDO_DANIEL_RAUBER,
    LEONARDO_FANEZE_CAMBOIM,
    LUCAS_MARTINS_ARAUJO_,
    MARIANA_SILVA_NASCIMENTO_DOS_REIS,
    PEDRO_DAPPER_ANTONETTI,
    RAFAEL_CAMILO_DE_OLIVEIRA,
    RENAN_DOS_SANTOS_MEIRA,
    RENATA_OLIVEIRA_SCHAFER,
    SHAIENNE_OLIVEIRA_DOS_SANTOS,
    THALES_XIMENES_BRASILEIRO,
    TIAGO_RAUPP_DA_ROSA,
    VICTOR_PRUDENTE_MACIEL,
    VINÍCIUS_FÉLIX_SANTOS_DE_JESUS,
    WLADMIR_DE_SOUZA_RODRIGUES;

}