
SELECT * FROM VEM_SER.PAIS p ORDER BY nome DESC;

SELECT logradouro, cep FROM VEM_SER.ENDERECO e WHERE logradouro LIKE 'a%' OR logradouro LIKE 'A%';
SELECT * FROM VEM_SER.ENDERECO e WHERE cep LIKE '%0';

SELECT * FROM VEM_SER.ENDERECO e WHERE numero BETWEEN 1 AND 100;

SELECT * FROM VEM_SER.ENDERECO e WHERE UPPER(logradouro) LIKE 'RUA%' ORDER BY cep DESC; 

SELECT COUNT(*) AS quantidade_enderecos FROM VEM_SER.ENDERECO;

SELECT COUNT(*) AS quantidade_enderecos FROM VEM_SER.ENDERECO GROUP BY id_cidade;

